# Generated by Django 5.1.3 on 2024-11-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0003_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='prefession',
            new_name='profession',
        ),
    ]
